<a href="https://colab.research.google.com/github/aldoxd82/optimizacion1D/blob/master/Met%C3%B3do_de_Gauss_Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Métodos iterativos.

Hasta ahora, hemos trabajado con métodos directos de solución. La característica común de estos métodos es que encuentran una solución a través de realizar unas serie de cálculos finitos. Si la computadora fuera capaz de una precisión infinita, la solución sería exacta.

Por otra parte, los métodos iterativos, utilizan una estimación inicial de la solución x y la van refinando de manera iterativa hasta que el error sea despreciable. Una de las desventajas de estos métodos es que no siempre convergen a una solución.

A continuación vamos a introducir el Método Gauss-Seidel para la solución de Sistemas de Ecuaciones Lineales.

## Método Gauss-Seidel

Podemos escribir las ecuaciones $Ax=b$ en notación escalar:

$$\sum_{j=1}^{n}A_{ij}x_{j}=b_i, \quad    i=1,2,..,n$$

Si extraemos de la sumatoria al término $x_i$

$$ A_{ii}x_i+\sum_{\begin{array}{lcl} j=1 \\ j \ne i \end{array}}^{n}A_{ij}x_{j}=b_i, \quad    i=1,2,..,n$$

Ahora podemos despejar a $x_i$

$$ x_i=\frac{1}{A_{ii}} \left( b_i-\sum_{\begin{array}{lcl} j=1 \\ j \ne i \end{array}}^{n}A_{ij}x_{j} \right), \quad    i=1,2,..,n$$

Lo que sugiere un esquema iterativo como el que sigue

$$ x_i \leftarrow \frac{1}{A_{ii}} \left( b_i-\sum_{\begin{array}{lcl} j=1 \\ j \ne i \end{array}}^{n}A_{ij}x_{j} \right), \quad    i=1,2,..,n$$

Empezamos eligiendo el vector inicial $x$, si no existe una aproximación adecuada, podemos elegir a x de manera arbitraria.

In [ ]:
import numpy as np
def seidel(A,b):
    n=len(b) #Determinamos el número de incógnitas.
    x=np.zeros(n) #Generamos un vector dependiendo el número de incógnitas
    
    for i in range (n):
        suma=0
        for j in range (n):
            if(j!=i):
                suma-=A[i][j]*x[j]                
            x[i]=(b[i]+suma)/A[i][i]
        print("x["+str(i)+"]:",x[i])        

In [ ]:
A = [[4, 1, 2],[3, 5, 1],[1, 1, 3]] 
b = [4,7,3]
seidel(A,b) 

x[0]: 1.0
x[1]: 0.8
x[2]: 0.39999999999999997


In [ ]:
import matplotlib.pyplot as plt
import math

def AlgIterativo(valorActual,iteracionMaxima,errorMinimo):
    contadorIteraciones=0
    valorAnterior=0
    errorActual=0;
    vectorX=[]
    vectorY=[]
    while(1):
        valorAnterior=valorActual
        valorActual=f(valorActual)
        contadorIteraciones=contadorIteraciones+1
        errorActual=abs((valorAnterior-valorActual)/valorActual)
        
        vectorX.append(contadorIteraciones)
        vectorY.append(valorActual)
        
        if (errorActual<=errorMinimo):
            fig, ax = plt.subplots()
            ax.scatter(vectorX, vectorY)
            plt.show()
            return valorActual
        elif (contadorIteraciones==iteracionMaxima):
            print("Se alcanzaron las iteraciones máximas")
            fig, ax = plt.subplots()
            ax.scatter(vectorX, vectorY)
            plt.show()
            break
        print("Iteración "+ str(contadorIteraciones) +": "+ str(valorActual))
        #print(vectorX)
        #print(vectorY)
    
def f(x):
    return (math.cos(x))

In [ ]:
import numpy as np
def seidel(A,b,IteracionMaxima):
  n=len(b)
  contadorIteraciones=0
  x=np.zeros(n)
  x_old=np.zeros(n)
  errorActual=np.zeros(n)
  while(1):
    print("Iteracion: " + str(contadorIteraciones+1)+ ":")
    contadorIteraciones=contadorIteraciones+1
    for i in range (n):
      suma=0
      for j in range (n):
        if(j!=i):
           suma=A[i][j]*x[j]
      x[i]=(b[i]+suma)/A[i][i]

    print(x)
    print(errorActual)
    x_old=x

    for i in range(n):
      errorActual[i]=abs((x_old[i]-x[i]/x[i]))

    if(contadorIteraciones==IteracionMaxima):
      break

In [ ]:
A=[[4,1,2],[3,5,1],[1,1,3]]
b=[4,7,3]
seidel(A,b,10)

Iteracion: 1:
[1.         1.4        1.46666667]
[0. 0. 0.]
Iteracion: 2:
[1.73333333 1.69333333 1.56444444]
[0.         0.4        0.46666667]
Iteracion: 3:
[1.78222222 1.71288889 1.57096296]
[0.73333333 0.69333333 0.56444444]
Iteracion: 4:
[1.78548148 1.71419259 1.57139753]
[0.78222222 0.71288889 0.57096296]
Iteracion: 5:
[1.78569877 1.71427951 1.5714265 ]
[0.78548148 0.71419259 0.57139753]
Iteracion: 6:
[1.78571325 1.7142853  1.57142843]
[0.78569877 0.71427951 0.5714265 ]
Iteracion: 7:
[1.78571422 1.71428569 1.57142856]
[0.78571325 0.7142853  0.57142843]
Iteracion: 8:
[1.78571428 1.71428571 1.57142857]
[0.78571422 0.71428569 0.57142856]
Iteracion: 9:
[1.78571429 1.71428571 1.57142857]
[0.78571428 0.71428571 0.57142857]
Iteracion: 10:
[1.78571429 1.71428571 1.57142857]
[0.78571429 0.71428571 0.57142857]
