<a href="https://colab.research.google.com/github/aldoxd82/optimizacion1D/blob/master/Pr%C3%A1ctica_2_T%C3%A9cnicas_de_pivoteo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pivoteo parcial por filas
# Solución a Sistemas de Ecuaciones

import numpy as np

# INGRESO
A = np.array([[0.003000,59.14],
              [5.291,-61.30]])

B = np.array([[59.27],
              [46.78]])

# PROCEDIMIENTO
# Matriz aumentada
AB  = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:]  = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal

# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB)

Matriz aumentada:
[[ 3.000e-03  5.914e+01  5.927e+01]
 [ 5.291e+00 -6.130e+01  4.678e+01]]
Pivoteo parcial por filas
[[ 5.291e+00 -6.130e+01  4.678e+01]
 [ 3.000e-03  5.914e+01  5.927e+01]]
